public class gateAnimationOnline {
	public static final AnimationDefinition online = AnimationDefinition.Builder.withLength(6.7917F).looping()
			.addAnimation("gate",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 7.5F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.0F, KeyframeAnimations.degreeVec(1.3096F, 7.3854F, 10.0845F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.0F, KeyframeAnimations.degreeVec(0.329F, 7.4928F, 2.5215F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.0F, KeyframeAnimations.degreeVec(-0.1101F, -10.0117F, 4.9597F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.9583F, KeyframeAnimations.degreeVec(-0.1093F, 7.4882F, 4.9263F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.0F, KeyframeAnimations.degreeVec(-10.1084F, -0.0117F, 4.9406F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.7083F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("gate",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, -2.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.0F, KeyframeAnimations.posVec(0.0F, 2.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.0F, KeyframeAnimations.posVec(0.0F, -1.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.0F, KeyframeAnimations.posVec(0.0F, -2.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.0F, KeyframeAnimations.posVec(0.0F, 2.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.75F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("rightup",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.6667F, KeyframeAnimations.degreeVec(-14.4817F, 9.9319F, 33.735F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.5F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.1667F, KeyframeAnimations.degreeVec(-14.4817F, 9.9319F, 33.735F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.0F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.0F, KeyframeAnimations.degreeVec(-4.8541F, -17.7577F, -15.682F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.8333F, KeyframeAnimations.degreeVec(5.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.6667F, KeyframeAnimations.degreeVec(11.6464F, -3.9204F, -1.7504F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.75F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("rightup",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 4.0F, -2.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.6667F, KeyframeAnimations.posVec(4.0F, 3.0F, -2.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.5F, KeyframeAnimations.posVec(0.0F, 4.0F, -2.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.1667F, KeyframeAnimations.posVec(4.0F, 3.0F, -2.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.0F, KeyframeAnimations.posVec(0.0F, 4.0F, -2.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.0F, KeyframeAnimations.posVec(-4.0F, 3.0F, -2.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.8333F, KeyframeAnimations.posVec(0.0F, -1.0F, -2.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.6667F, KeyframeAnimations.posVec(-4.0F, 2.0F, -2.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.75F, KeyframeAnimations.posVec(0.0F, 4.0F, -2.0F),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("left",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8333F, KeyframeAnimations.degreeVec(-9.5436F, 2.7151F, 2.5788F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.4167F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.25F, KeyframeAnimations.degreeVec(-9.5436F, 2.7151F, 2.5788F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.8333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.6667F, KeyframeAnimations.degreeVec(-9.5436F, 2.7151F, 2.5788F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.25F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.0833F, KeyframeAnimations.degreeVec(-9.5436F, 2.7151F, 2.5788F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.7083F, KeyframeAnimations.degreeVec(-9.5436F, 2.7151F, 2.5788F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.2917F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.75F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("left",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8333F, KeyframeAnimations.posVec(0.0F, 2.0F, 3.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.4167F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.25F, KeyframeAnimations.posVec(0.0F, 2.0F, 3.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.8333F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.6667F, KeyframeAnimations.posVec(0.0F, 2.0F, 3.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.25F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.0833F, KeyframeAnimations.posVec(0.0F, 2.0F, 3.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.7083F, KeyframeAnimations.posVec(0.0F, 2.0F, 3.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.2917F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.75F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leftup",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(31.25F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.5F, KeyframeAnimations.degreeVec(23.75F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.0F, KeyframeAnimations.degreeVec(13.75F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.3333F, KeyframeAnimations.degreeVec(23.75F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.6667F, KeyframeAnimations.degreeVec(31.25F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.1667F, KeyframeAnimations.degreeVec(23.75F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.6667F, KeyframeAnimations.degreeVec(13.75F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.0F, KeyframeAnimations.degreeVec(23.75F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.3333F, KeyframeAnimations.degreeVec(31.25F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.8333F, KeyframeAnimations.degreeVec(23.75F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.3333F, KeyframeAnimations.degreeVec(13.75F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.6667F, KeyframeAnimations.degreeVec(23.75F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.0F, KeyframeAnimations.degreeVec(31.25F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.5F, KeyframeAnimations.degreeVec(23.75F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.0F, KeyframeAnimations.degreeVec(13.75F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.3333F, KeyframeAnimations.degreeVec(23.75F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.6667F, KeyframeAnimations.degreeVec(31.25F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leftup",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 4.0F, 2.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.5F, KeyframeAnimations.posVec(0.0F, 6.0F, 2.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 9.0F, 2.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.3333F, KeyframeAnimations.posVec(0.0F, 7.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.6667F, KeyframeAnimations.posVec(0.0F, 4.0F, 2.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.1667F, KeyframeAnimations.posVec(0.0F, 6.0F, 2.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.6667F, KeyframeAnimations.posVec(0.0F, 9.0F, 2.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.0F, KeyframeAnimations.posVec(0.0F, 7.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.3333F, KeyframeAnimations.posVec(0.0F, 4.0F, 2.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.8333F, KeyframeAnimations.posVec(0.0F, 6.0F, 2.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.3333F, KeyframeAnimations.posVec(0.0F, 9.0F, 2.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.6667F, KeyframeAnimations.posVec(0.0F, 7.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.0F, KeyframeAnimations.posVec(0.0F, 4.0F, 2.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.5F, KeyframeAnimations.posVec(0.0F, 6.0F, 2.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.0F, KeyframeAnimations.posVec(0.0F, 9.0F, 2.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.3333F, KeyframeAnimations.posVec(0.0F, 7.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.6667F, KeyframeAnimations.posVec(0.0F, 4.0F, 2.0F),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("table",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.375F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.9583F, KeyframeAnimations.degreeVec(157.5F, 0.0F, 259.7452F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.25F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 370.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 378.44F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.75F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("table",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 12.5F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 20.5F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.0F, KeyframeAnimations.posVec(0.0F, 12.5F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.0F, KeyframeAnimations.posVec(0.0F, 20.5F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.0F, KeyframeAnimations.posVec(0.0F, 12.5F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.0F, KeyframeAnimations.posVec(0.0F, 20.5F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.0F, KeyframeAnimations.posVec(0.0F, 28.5F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.75F, KeyframeAnimations.posVec(0.0F, 12.5F, 0.0F),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("portallayerone",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("portallayertwo",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("portallayerthree",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("crystal",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("crystal",
					new AnimationChannel(AnimationChannel.Targets.POSITION, new Keyframe(0.0F,
							KeyframeAnimations.posVec(2.6F, 2.4F, -1.3F), AnimationChannel.Interpolations.LINEAR)))
			.build();
}